config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :profiles do
    resources :users, only: [:show]
  end

  root "main#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :surname, :phone_number, :location, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :surname, :phone_number, :location, :email])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/profiles/users_controller.rb
module Profiles
  class UsersController < ApplicationController
    def show
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="text-3xl font-bold underline">
    The main page
</h1>
<div class="mt-6 sm:w-full sm:max-w-sm">
    <%= link_to 'Profile user', profiles_user_path(@user), class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm leading-6 text-white shadow-sm hover:bg-indigo-500" %>
</div>

app/views/profiles/users/show.html.erb
<div class="flex items-center justify-center mt-20">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <div class="mx-auto mb-4">
      <img class="mx-auto h-10 w-auto mb-4" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
      <h2 class="text-center text-3xl font-bold text-green">Profile</h2>
    </div>

    <div class="mt-4 sm:w-full sm:max-w-sm">
      <p class="block text-sm font-medium leading-6 text-gray-900">Username</p>
      <p class="w-full py-2 px-3 border rounded-md focus:ring focus:ring-green-300"><%= @user.username %></p>
    </div>

    <div class="mt-4 sm:w-full sm:max-w-sm">
      <p class="block text-sm font-medium leading-6 text-gray-900">Surname</p>
      <p class="w-full py-2 px-3 border rounded-md focus:ring focus:ring-green-300"><%= @user.surname %></p>
    </div>

    <div class="mt-4 sm:w-full sm:max-w-sm">
      <p class="block text-sm font-medium leading-6 text-gray-900">Location</p>
      <p class="w-full py-2 px-3 border rounded-md focus:ring focus:ring-green-300"><%= @user.location %></p>
    </div>

    <div class="mt-4 sm:w-full sm:max-w-sm">
      <p class="block text-sm font-medium leading-6 text-gray-900">Phone Number</p>
      <p class="w-full py-2 px-3 border rounded-md focus:ring focus:ring-green-300"><%= @user.phone_number %></p>
    </div>

    <div class="mt-4 sm:w-full sm:max-w-sm">
      <p class="block text-sm font-medium leading-6 text-gray-900">Email</p>
      <p class="w-full py-2 px-3 border rounded-md focus:ring focus:ring-green-300"><%= @user.email %></p>
    </div>

    <div class="mt-6 sm:w-full sm:max-w-sm">
      <%= link_to 'Edit Profile', edit_user_registration_path(@user), class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm leading-6 text-white shadow-sm hover:bg-indigo-500" %>
    </div>
  </div>
</div>